TebLocalPlannerROS:

 odom_topic: /odometry/filtered
 map_frame: map
    
 # Trajectory
 teb_autosize: True
 global_plan_viapoint_sep: 2.00
 dt_ref: 0.50
 dt_hysteresis: 0.05
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 10.0
 feasibility_check_no_poses: 3
    
 # Robot
 max_vel_x: 1.8
 max_vel_x_backwards: 0.7
 max_vel_y: 0.0                  # 必须为0，阿克曼底盘无法横移
 max_vel_theta: 1.0            
 acc_lim_x: 0.5
 acc_lim_theta: 0.5

 # ********************** 阿克曼运动学 (Ackermann) **************************
 min_turning_radius: 0.10        # 最小转弯半径，禁止原地旋转
 wheelbase: 0.50                # 轴距，可根据实际底盘调整
 cmd_angle_instead_rotvel: False # 因为底层控制器接收的是 Twist (v, w) 计算转角
 # **************************************************************


 footprint_model:
   type: "polygon"
   vertices: [[-0.36, -0.25], [-0.36, 0.25], [0.36, 0.25], [0.36, -0.25]]

 # GoalTolerance
 xy_goal_tolerance: 0.3
 yaw_goal_tolerance: 0.6
 free_goal_vel: False
    
 # Obstacles
 min_obstacle_dist: 0.2
 inflation_dist: 0.3
 include_dynamic_obstacles: True
 dynamic_obstacle_inflation_dist: 0.5
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: "costmap_converter::CostmapToDynamicObstacles"
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization 
 no_inner_iterations: 4
 no_outer_iterations: 3
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_y: 0
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1.5
 weight_acc_lim_theta: 1.5
 weight_kinematics_nh: 1000      # 极高权重：强迫像汽车一样满足非完整约束
 weight_kinematics_forward_drive: 1000 # 极高权重：强迫尽量向前开，禁止随意倒车
 weight_kinematics_turning_radius: 1   # 注意如果这里太高可能会导致无解
 weight_optimaltime: 0.2
 weight_viapoint: 20.0
 weight_obstacle: 100
 weight_dynamic_obstacle: 20 

 # Homotopy Class Planner
 enable_homotopy_class_planning: False
 max_number_classes: 1
 selection_cost_hysteresis: 0.5
